### ISSUE TITLE
Tile Generation

### ISSUE THREAD

**Issue by Serpent03** [ballisticfox/MapTheEarth-KSP#1]
How exactly do you generate tiles? Is there any process/tool for it?

**Comment by Serpent03** [comment]
@ballisticfox nudge

**Comment by ballisticfox** [comment]
https://github.com/ballisticfox/MapTheEarth-KSP/wiki/Creating-a-usable-heightmap-%7C-3DEP-Dataset-(US)

**Comment by Serpent03** [comment]
Thanks very much
